# Generated by Django 6.1 for F-001 Step 0. Do not edit after merge.

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("platform_database", "0001_platform_baseline")]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider_subject", models.UUIDField(editable=False, unique=True)),
                ("status", models.CharField(default="active", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
            ],
            options={
                "db_table": 'app"."user_profiles',
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ("active", "inactive"))),
                        name="ck_user_profiles_status",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE app.user_profiles OWNER TO lms_object_owner;
                REVOKE ALL ON TABLE app.user_profiles FROM PUBLIC;
            """,
            reverse_sql="""
                ALTER TABLE app.user_profiles OWNER TO CURRENT_USER;
            """,
        ),
    ]
