# Generated by Django 6.1 on 2026-08-22 08:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0002_secure_invitation_bootstrap"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("display_name", models.CharField(max_length=160)),
                ("owner_actor_id", models.UUIDField()),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'app"."source_documents',
            },
        ),
        migrations.CreateModel(
            name="SourceRightsDeclaration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("declared_by_actor_id", models.UUIDField()),
                ("basis", models.CharField(max_length=32)),
                ("attestation_version", models.CharField(max_length=64)),
                ("attested_at", models.DateTimeField()),
                ("rights_holder_name", models.CharField(blank=True, max_length=160, null=True)),
                ("evidence_reference", models.CharField(blank=True, max_length=120, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.sourcedocument"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'app"."source_rights_declarations',
            },
        ),
        migrations.CreateModel(
            name="SourceVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version_number", models.PositiveIntegerField(default=1)),
                ("admission_status", models.CharField(default="rights_pending", max_length=24)),
                ("declared_filename", models.CharField(max_length=255)),
                ("content_sha256", models.CharField(blank=True, max_length=71, null=True)),
                ("derived_file_size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("derived_media_type", models.CharField(blank=True, max_length=100, null=True)),
                ("derived_pdf_signature_valid", models.BooleanField(blank=True, null=True)),
                ("derived_parser_accepted", models.BooleanField(blank=True, null=True)),
                ("derived_page_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "derived_max_rendered_pixels_per_page",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "derived_rendered_pixels_total",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "derived_decoded_parser_bytes",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "derived_local_inspection_result",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("rejection_code", models.CharField(blank=True, max_length=80, null=True)),
                ("validation_attempt_count", models.PositiveIntegerField(default=0)),
                ("removal_status", models.CharField(default="not_required", max_length=16)),
                ("removal_reason_code", models.CharField(blank=True, max_length=32, null=True)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="versions",
                        to="documents.sourcedocument",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'app"."source_document_versions',
            },
        ),
        migrations.CreateModel(
            name="SourceUseAuthorization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("operation", models.CharField(default="store", max_length=16)),
                ("status", models.CharField(default="requested", max_length=16)),
                ("requested_by_actor_id", models.UUIDField()),
                ("reviewed_by_actor_id", models.UUIDField(blank=True, null=True)),
                ("decision_code", models.CharField(blank=True, max_length=64, null=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "rights_declaration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="documents.sourcerightsdeclaration",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.sourcedocument"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.sourceversion"
                    ),
                ),
            ],
            options={
                "db_table": 'app"."source_use_authorizations',
            },
        ),
        migrations.AddField(
            model_name="sourcerightsdeclaration",
            name="source_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.sourceversion"
            ),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="current_for_documents",
                to="documents.sourceversion",
            ),
        ),
        migrations.CreateModel(
            name="StorageObject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("private_locator", models.CharField(max_length=80, unique=True)),
                ("content_sha256", models.CharField(max_length=71)),
                ("byte_count", models.PositiveBigIntegerField()),
                ("media_type", models.CharField(max_length=100)),
                ("status", models.CharField(default="present", max_length=16)),
                ("observed_at", models.DateTimeField()),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.sourcedocument"
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.sourceversion"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'app"."source_storage_objects',
            },
        ),
        migrations.CreateModel(
            name="DocumentJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stage", models.CharField(max_length=32)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("reason_code", models.CharField(blank=True, max_length=80, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("lease_owner", models.CharField(blank=True, max_length=80, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("checkpoint", models.CharField(default="created", max_length=64)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("correlation_id", models.UUIDField(default=uuid.uuid4)),
                ("input_manifest_sha256", models.CharField(max_length=71)),
                ("output_manifest_sha256", models.CharField(blank=True, max_length=71, null=True)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.sourcedocument"
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.sourceversion"
                    ),
                ),
                (
                    "storage_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.storageobject"
                    ),
                ),
            ],
            options={
                "db_table": 'integration"."document_jobs',
            },
        ),
        migrations.CreateModel(
            name="UploadIntent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token_digest", models.CharField(editable=False, max_length=64, unique=True)),
                ("purpose", models.CharField(default="source_quarantine", max_length=32)),
                ("status", models.CharField(default="active", max_length=16)),
                ("expires_at", models.DateTimeField()),
                ("max_bytes", models.PositiveBigIntegerField()),
                (
                    "accepted_media_type",
                    models.CharField(default="application/pdf", max_length=100),
                ),
                ("observed_content_sha256", models.CharField(blank=True, max_length=71, null=True)),
                ("observed_byte_count", models.PositiveBigIntegerField(blank=True, null=True)),
                ("upload_claim_digest", models.CharField(blank=True, max_length=64, null=True)),
                ("upload_claim_expires_at", models.DateTimeField(blank=True, null=True)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "authorization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="documents.sourceuseauthorization",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.sourcedocument"
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.sourceversion"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'app"."source_upload_intents',
            },
        ),
        migrations.AddField(
            model_name="storageobject",
            name="upload_intent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.uploadintent"
            ),
        ),
        migrations.CreateModel(
            name="DocumentJobAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                ("outcome", models.CharField(default="running", max_length=16)),
                ("retry_class", models.CharField(blank=True, max_length=32, null=True)),
                ("reason_code", models.CharField(blank=True, max_length=80, null=True)),
                ("inspector_version", models.CharField(blank=True, max_length=80, null=True)),
                ("input_manifest_sha256", models.CharField(max_length=71)),
                ("output_manifest_sha256", models.CharField(blank=True, max_length=71, null=True)),
                ("observation", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="attempts",
                        to="documents.documentjob",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'integration"."document_job_attempts',
                "indexes": [
                    models.Index(
                        fields=["tenant", "job", "attempt_number"], name="ix_doc_attempts_job"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="uq_document_attempts_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "job", "attempt_number"),
                        name="uq_document_attempts_job_number",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "outcome__in",
                                ("running", "completed", "retryable", "failed", "cancelled"),
                            )
                        ),
                        name="ck_document_attempts_outcome",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sourceversion",
            index=models.Index(
                fields=["tenant", "admission_status"], name="ix_source_versions_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceversion",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_source_versions_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceversion",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_document", "id"), name="uq_source_versions_tenant_doc_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceversion",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_document", "version_number"),
                name="uq_source_versions_doc_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "admission_status__in",
                        (
                            "rights_pending",
                            "upload_pending",
                            "quarantined",
                            "validating",
                            "admitted",
                            "rejected",
                            "cancelled",
                            "blocked",
                        ),
                    )
                ),
                name="ck_source_versions_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("removal_status__in", ("not_required", "pending", "completed", "failed"))
                ),
                name="ck_source_versions_removal_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("content_sha256__isnull", True),
                    ("content_sha256__regex", "^sha256:[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="ck_source_versions_checksum",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("row_version__gte", 1)), name="ck_source_versions_row_version"
            ),
        ),
        migrations.AddIndex(
            model_name="sourceuseauthorization",
            index=models.Index(
                fields=["tenant", "source_version", "operation", "status"],
                name="ix_source_auth_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceuseauthorization",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_source_auth_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceuseauthorization",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_version", "operation"),
                name="uq_source_auth_version_operation",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceuseauthorization",
            constraint=models.CheckConstraint(
                condition=models.Q(("operation", "store")), name="ck_source_auth_store_only"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceuseauthorization",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ("requested", "active", "denied", "revoked", "expired", "disputed"),
                    )
                ),
                name="ck_source_auth_status",
            ),
        ),
        migrations.AddIndex(
            model_name="sourcerightsdeclaration",
            index=models.Index(
                fields=["tenant", "source_version"], name="ix_source_rights_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerightsdeclaration",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_source_rights_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerightsdeclaration",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_version"), name="uq_source_rights_version"
            ),
        ),
        migrations.AddIndex(
            model_name="sourcedocument",
            index=models.Index(fields=["tenant", "owner_actor_id"], name="ix_source_docs_owner"),
        ),
        migrations.AddConstraint(
            model_name="sourcedocument",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_source_documents_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(("row_version__gte", 1)), name="ck_source_documents_row_version"
            ),
        ),
        migrations.AddIndex(
            model_name="documentjob",
            index=models.Index(fields=["tenant", "stage", "status"], name="ix_document_jobs_claim"),
        ),
        migrations.AddConstraint(
            model_name="documentjob",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_document_jobs_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentjob",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_version", "stage"), name="uq_document_jobs_version_stage"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("stage__in", ("validate_admission", "remove_quarantine_object"))
                ),
                name="ck_document_jobs_stage",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ("pending", "claimed", "retryable", "completed", "failed", "cancelled"),
                    )
                ),
                name="ck_document_jobs_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_manifest_sha256__regex", "^sha256:[0-9a-f]{64}$")),
                name="ck_document_jobs_input_hash",
            ),
        ),
        migrations.AddIndex(
            model_name="uploadintent",
            index=models.Index(
                fields=["tenant", "status", "expires_at"], name="ix_source_intents_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="uploadintent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_source_intents_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="uploadintent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("tenant", "source_version"),
                name="uq_source_intents_active_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="uploadintent",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("active", "consumed", "expired", "cancelled"))),
                name="ck_source_intents_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="uploadintent",
            constraint=models.CheckConstraint(
                condition=models.Q(("purpose", "source_quarantine")),
                name="ck_source_intents_purpose",
            ),
        ),
        migrations.AddIndex(
            model_name="storageobject",
            index=models.Index(fields=["tenant", "status"], name="ix_source_objects_status"),
        ),
        migrations.AddConstraint(
            model_name="storageobject",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_source_objects_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="storageobject",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_version"), name="uq_source_objects_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="storageobject",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("present", "missing", "deleted"))),
                name="ck_source_objects_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="storageobject",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_sha256__regex", "^sha256:[0-9a-f]{64}$")),
                name="ck_source_objects_checksum",
            ),
        ),
    ]
