# Generated by Django 6.1 on 2026-08-31 02:09

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_document_security"),
        ("tenancy", "0002_secure_invitation_bootstrap"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentElement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("kind", models.CharField(max_length=16)),
                ("text", models.TextField()),
                ("text_sha256", models.CharField(max_length=71)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": 'app"."document_elements',
            },
        ),
        migrations.CreateModel(
            name="DocumentIngestionAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                ("outcome", models.CharField(default="running", max_length=24)),
                ("reason_code", models.CharField(blank=True, max_length=80, null=True)),
                ("checkpoint", models.CharField(default="claimed", max_length=64)),
                ("input_manifest_sha256", models.CharField(max_length=71)),
                ("output_manifest_sha256", models.CharField(blank=True, max_length=71, null=True)),
                ("observation", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": 'integration"."document_ingestion_attempts',
            },
        ),
        migrations.CreateModel(
            name="DocumentIngestionRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("requested_by_actor_id", models.UUIDField()),
                ("status", models.CharField(default="queued", max_length=24)),
                ("parser_version", models.CharField(max_length=80)),
                ("configuration_version", models.CharField(max_length=64)),
                ("locale", models.CharField(default="en", max_length=8)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("lease_owner", models.CharField(blank=True, max_length=80, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("checkpoint", models.CharField(default="created", max_length=64)),
                ("input_manifest_sha256", models.CharField(max_length=71)),
                ("output_manifest_sha256", models.CharField(blank=True, max_length=71, null=True)),
                ("reason_code", models.CharField(blank=True, max_length=80, null=True)),
                ("quality_summary", models.JSONField(default=dict)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
            ],
            options={
                "db_table": 'integration"."document_ingestion_runs',
            },
        ),
        migrations.CreateModel(
            name="DocumentPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("parser_version", models.CharField(max_length=80)),
                ("configuration_version", models.CharField(max_length=64)),
                ("page_number", models.PositiveIntegerField()),
                ("width_points", models.DecimalField(decimal_places=3, max_digits=12)),
                ("height_points", models.DecimalField(decimal_places=3, max_digits=12)),
                ("text", models.TextField()),
                ("text_sha256", models.CharField(max_length=71)),
                ("ocr_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": 'app"."document_pages',
            },
        ),
        migrations.CreateModel(
            name="DocumentSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=160)),
                ("start_page", models.PositiveIntegerField()),
                ("end_page", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": 'app"."document_sections',
            },
        ),
        migrations.CreateModel(
            name="DocumentSectionElement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": 'app"."document_section_elements',
            },
        ),
        migrations.CreateModel(
            name="SourceArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("artifact_role", models.CharField(max_length=24)),
                ("schema_version", models.CharField(max_length=64)),
                ("content_sha256", models.CharField(max_length=71)),
                ("byte_count", models.PositiveBigIntegerField()),
                ("json_payload", models.JSONField(blank=True, null=True)),
                ("text_payload", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": 'app"."source_artifacts',
            },
        ),
        migrations.RemoveConstraint(
            model_name="sourceuseauthorization",
            name="ck_source_auth_store_only",
        ),
        migrations.AddConstraint(
            model_name="sourceuseauthorization",
            constraint=models.CheckConstraint(
                condition=models.Q(("operation__in", ("store", "extract", "ocr", "generate"))),
                name="ck_source_auth_operation",
            ),
        ),
        migrations.AddField(
            model_name="documentelement",
            name="source_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.sourcedocument"
            ),
        ),
        migrations.AddField(
            model_name="documentelement",
            name="source_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.sourceversion"
            ),
        ),
        migrations.AddField(
            model_name="documentelement",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
            ),
        ),
        migrations.AddField(
            model_name="documentingestionattempt",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
            ),
        ),
        migrations.AddField(
            model_name="documentingestionrun",
            name="extract_authorization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.sourceuseauthorization"
            ),
        ),
        migrations.AddField(
            model_name="documentingestionrun",
            name="source_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.sourcedocument"
            ),
        ),
        migrations.AddField(
            model_name="documentingestionrun",
            name="source_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.sourceversion"
            ),
        ),
        migrations.AddField(
            model_name="documentingestionrun",
            name="storage_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.storageobject"
            ),
        ),
        migrations.AddField(
            model_name="documentingestionrun",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
            ),
        ),
        migrations.AddField(
            model_name="documentingestionattempt",
            name="ingestion_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="attempts",
                to="documents.documentingestionrun",
            ),
        ),
        migrations.AddField(
            model_name="documentelement",
            name="created_by_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.documentingestionrun"
            ),
        ),
        migrations.AddField(
            model_name="documentpage",
            name="created_by_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.documentingestionrun"
            ),
        ),
        migrations.AddField(
            model_name="documentpage",
            name="source_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.sourcedocument"
            ),
        ),
        migrations.AddField(
            model_name="documentpage",
            name="source_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.sourceversion"
            ),
        ),
        migrations.AddField(
            model_name="documentpage",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
            ),
        ),
        migrations.AddField(
            model_name="documentelement",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="elements",
                to="documents.documentpage",
            ),
        ),
        migrations.AddField(
            model_name="documentsection",
            name="created_by_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.documentingestionrun"
            ),
        ),
        migrations.AddField(
            model_name="documentsection",
            name="source_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.sourcedocument"
            ),
        ),
        migrations.AddField(
            model_name="documentsection",
            name="source_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.sourceversion"
            ),
        ),
        migrations.AddField(
            model_name="documentsection",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
            ),
        ),
        migrations.AddField(
            model_name="documentsectionelement",
            name="element",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.documentelement"
            ),
        ),
        migrations.AddField(
            model_name="documentsectionelement",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="element_edges",
                to="documents.documentsection",
            ),
        ),
        migrations.AddField(
            model_name="documentsectionelement",
            name="source_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.sourceversion"
            ),
        ),
        migrations.AddField(
            model_name="documentsectionelement",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
            ),
        ),
        migrations.AddField(
            model_name="sourceartifact",
            name="created_by_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.documentingestionrun"
            ),
        ),
        migrations.AddField(
            model_name="sourceartifact",
            name="source_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.sourcedocument"
            ),
        ),
        migrations.AddField(
            model_name="sourceartifact",
            name="source_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="documents.sourceversion"
            ),
        ),
        migrations.AddField(
            model_name="sourceartifact",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="documentingestionrun",
            index=models.Index(
                fields=["tenant", "status", "created_at"], name="ix_ingest_runs_claim"
            ),
        ),
        migrations.AddIndex(
            model_name="documentingestionrun",
            index=models.Index(
                fields=["tenant", "source_version", "created_at"], name="ix_ingest_runs_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentingestionrun",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_ingestion_runs_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentingestionrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "queued",
                            "claimed",
                            "extracting",
                            "normalizing",
                            "quality_check",
                            "retryable",
                        ),
                    )
                ),
                fields=("tenant", "source_version", "parser_version", "configuration_version"),
                name="uq_ingestion_runs_active_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentingestionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "queued",
                            "claimed",
                            "extracting",
                            "normalizing",
                            "quality_check",
                            "ready_for_generation",
                            "retryable",
                            "failed",
                            "cancelled",
                            "rights_blocked",
                        ),
                    )
                ),
                name="ck_ingestion_runs_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentingestionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("locale", "en")), name="ck_ingestion_runs_locale"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentingestionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_manifest_sha256__regex", "^sha256:[0-9a-f]{64}$")),
                name="ck_ingestion_runs_input_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentingestionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("output_manifest_sha256__isnull", True),
                    ("output_manifest_sha256__regex", "^sha256:[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="ck_ingestion_runs_output_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentingestionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_attempts__gte", 1),
                    ("max_attempts__lte", 10),
                    ("attempt_count__lte", models.F("max_attempts")),
                ),
                name="ck_ingestion_runs_attempts",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentingestionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("row_version__gte", 1)), name="ck_ingestion_runs_row_version"
            ),
        ),
        migrations.AddIndex(
            model_name="documentingestionattempt",
            index=models.Index(
                fields=["tenant", "ingestion_run", "attempt_number"], name="ix_ingest_attempts_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentingestionattempt",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_ingestion_attempts_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentingestionattempt",
            constraint=models.UniqueConstraint(
                fields=("tenant", "ingestion_run", "attempt_number"),
                name="uq_ingestion_attempts_run_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentingestionattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "outcome__in",
                        (
                            "running",
                            "completed",
                            "retryable",
                            "failed",
                            "cancelled",
                            "rights_blocked",
                        ),
                    )
                ),
                name="ck_ingestion_attempts_outcome",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentingestionattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_manifest_sha256__regex", "^sha256:[0-9a-f]{64}$")),
                name="ck_ingestion_attempts_input_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentingestionattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("output_manifest_sha256__isnull", True),
                    ("output_manifest_sha256__regex", "^sha256:[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="ck_ingestion_attempts_output_hash",
            ),
        ),
        migrations.AddIndex(
            model_name="documentpage",
            index=models.Index(
                fields=["tenant", "source_version", "page_number"], name="ix_document_pages_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentpage",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_document_pages_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentpage",
            constraint=models.UniqueConstraint(
                fields=(
                    "tenant",
                    "source_version",
                    "parser_version",
                    "configuration_version",
                    "page_number",
                ),
                name="uq_document_pages_version_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentpage",
            constraint=models.CheckConstraint(
                condition=models.Q(("page_number__gte", 1)), name="ck_document_pages_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentpage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("width_points__gt", Decimal("0")), ("height_points__gt", Decimal("0"))
                ),
                name="ck_document_pages_dimensions",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentpage",
            constraint=models.CheckConstraint(
                condition=models.Q(("text_sha256__regex", "^sha256:[0-9a-f]{64}$")),
                name="ck_document_pages_text_hash",
            ),
        ),
        migrations.AddIndex(
            model_name="documentelement",
            index=models.Index(
                fields=["tenant", "page", "position"], name="ix_document_elements_page"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentelement",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_document_elements_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentelement",
            constraint=models.UniqueConstraint(
                fields=("tenant", "page", "position"), name="uq_document_elements_page_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentelement",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)), name="ck_document_elements_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentelement",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ("heading", "paragraph"))),
                name="ck_document_elements_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentelement",
            constraint=models.CheckConstraint(
                condition=models.Q(("text_sha256__regex", "^sha256:[0-9a-f]{64}$")),
                name="ck_document_elements_text_hash",
            ),
        ),
        migrations.AddIndex(
            model_name="documentsection",
            index=models.Index(
                fields=["tenant", "source_version", "position"], name="ix_document_sections_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsection",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_document_sections_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsection",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_version", "position"),
                name="uq_document_sections_version_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsection",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)), name="ck_document_sections_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_page__gte", 1), ("end_page__gte", models.F("start_page"))
                ),
                name="ck_document_sections_page_range",
            ),
        ),
        migrations.AddIndex(
            model_name="documentsectionelement",
            index=models.Index(
                fields=["tenant", "section", "position"], name="ix_doc_section_elements"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsectionelement",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_document_section_elements_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsectionelement",
            constraint=models.UniqueConstraint(
                fields=("tenant", "section", "position"),
                name="uq_document_section_elements_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsectionelement",
            constraint=models.UniqueConstraint(
                fields=("tenant", "section", "element"), name="uq_document_section_elements_edge"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsectionelement",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)),
                name="ck_document_section_elements_position",
            ),
        ),
        migrations.AddIndex(
            model_name="sourceartifact",
            index=models.Index(
                fields=["tenant", "source_version", "artifact_role"],
                name="ix_source_artifacts_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceartifact",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_source_artifacts_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceartifact",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_version", "artifact_role", "schema_version"),
                name="uq_source_artifacts_version_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("artifact_role__in", ("canonical_json", "normalized_markdown"))
                ),
                name="ck_source_artifacts_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_sha256__regex", "^sha256:[0-9a-f]{64}$")),
                name="ck_source_artifacts_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("byte_count__gte", 1)), name="ck_source_artifacts_bytes"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("artifact_role", "canonical_json"),
                        ("json_payload__isnull", False),
                        ("text_payload__isnull", True),
                    ),
                    models.Q(
                        ("artifact_role", "normalized_markdown"),
                        ("json_payload__isnull", True),
                        ("text_payload__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_source_artifacts_payload",
            ),
        ),
    ]
