# Generated by Django 6.1 on 2026-08-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_ingestion_schema"),
        ("tenancy", "0002_secure_invitation_bootstrap"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="documentelement",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_version", "id"), name="uq_document_elements_tenant_ver_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentingestionrun",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_version", "id"), name="uq_ingestion_runs_tenant_ver_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentpage",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_version", "id"), name="uq_document_pages_tenant_ver_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsection",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_version", "id"), name="uq_document_sections_tenant_ver_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsectionelement",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_version", "id"),
                name="uq_document_section_elements_tenant_ver_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceartifact",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_version", "id"), name="uq_source_artifacts_tenant_ver_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceuseauthorization",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_version", "id"), name="uq_source_auth_tenant_ver_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="storageobject",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_version", "id"), name="uq_source_objects_tenant_ver_id"
            ),
        ),
    ]
