# Generated by Django 6.1 on 2026-08-22 14:04

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0003_one_successor"),
        ("tenancy", "0002_secure_invitation_bootstrap"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("admission_source", models.CharField(default="manual_assignment", max_length=24)),
                ("status", models.CharField(default="active", max_length=16)),
                ("enrolled_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason_code", models.CharField(blank=True, max_length=64, null=True)),
                ("assigned_by_actor_id", models.UUIDField(default=uuid.uuid4)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="learning_enrollments",
                        to="courses.course",
                    ),
                ),
                (
                    "course_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="learning_enrollments",
                        to="courses.courseversion",
                    ),
                ),
                (
                    "learner_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="learning_enrollments",
                        to="tenancy.tenantmembership",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="learning_enrollments",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."enrollments',
            },
        ),
        migrations.CreateModel(
            name="CourseProgress",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("state", models.CharField(default="not_started", max_length=16)),
                ("required_lesson_count", models.PositiveIntegerField()),
                ("completed_required_lesson_count", models.PositiveIntegerField(default=0)),
                ("last_progress_at", models.DateTimeField(blank=True, null=True)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "course_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="course_progress_rows",
                        to="courses.courseversion",
                    ),
                ),
                (
                    "resume_lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="resumed_course_progress_rows",
                        to="courses.lesson",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="course_progress_rows",
                        to="learning.enrollment",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."course_progress',
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("state", models.CharField(default="not_started", max_length=16)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "course_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="lesson_progress_rows",
                        to="courses.courseversion",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="lesson_progress_rows",
                        to="learning.enrollment",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="learner_progress_rows",
                        to="courses.lesson",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'app"."lesson_progress',
            },
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["tenant", "learner_membership", "status", "-enrolled_at", "-id"],
                name="ix_enrollments_dashboard",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["tenant", "course", "status"], name="ix_enrollments_course_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_enrollments_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("tenant", "learner_membership", "course"),
                name="uq_enrollments_active_learner_course",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(("admission_source__in", ("manual_assignment",))),
                name="ck_enrollments_admission_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("active", "revoked"))),
                name="ck_enrollments_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(("row_version__gte", 1)), name="ck_enrollments_row_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("revocation_reason_code__isnull", True),
                        ("revoked_at__isnull", True),
                        ("status", "active"),
                    ),
                    models.Q(
                        ("revoked_at__isnull", False),
                        ("status", "revoked"),
                        ("revocation_reason_code__regex", "^[A-Z][A-Z0-9_]{2,63}$"),
                    ),
                    _connector="OR",
                ),
                name="ck_enrollments_revocation_shape",
            ),
        ),
        migrations.AddIndex(
            model_name="courseprogress",
            index=models.Index(
                fields=["tenant", "enrollment"], name="ix_course_progress_enrollment"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseprogress",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_course_progress_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseprogress",
            constraint=models.UniqueConstraint(
                fields=("tenant", "enrollment"), name="uq_course_progress_enrollment"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseprogress",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ("not_started", "in_progress", "completed"))),
                name="ck_course_progress_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseprogress",
            constraint=models.CheckConstraint(
                condition=models.Q(("required_lesson_count__gte", 1)),
                name="ck_course_progress_required_count",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseprogress",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("completed_required_lesson_count__lte", models.F("required_lesson_count"))
                ),
                name="ck_course_progress_completed_count",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseprogress",
            constraint=models.CheckConstraint(
                condition=models.Q(("row_version__gte", 1)), name="ck_course_progress_row_version"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["tenant", "enrollment", "lesson"], name="ix_lesson_progress_lookup"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["tenant", "enrollment", "state"], name="ix_lesson_progress_state"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonprogress",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_lesson_progress_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonprogress",
            constraint=models.UniqueConstraint(
                fields=("tenant", "enrollment", "lesson"),
                name="uq_lesson_progress_enrollment_lesson",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonprogress",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ("not_started", "in_progress", "completed"))),
                name="ck_lesson_progress_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonprogress",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("completed_at__isnull", False), ("state", "completed")),
                    models.Q(
                        models.Q(("state", "completed"), _negated=True),
                        ("completed_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_lesson_progress_completion_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonprogress",
            constraint=models.CheckConstraint(
                condition=models.Q(("row_version__gte", 1)), name="ck_lesson_progress_row_version"
            ),
        ),
    ]
