# Generated by Django 6.1 on 2026-08-17 15:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0002_secure_invitation_bootstrap"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(max_length=63)),
                ("reviewer_policy", models.CharField(default="self_review_allowed", max_length=32)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="courses",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."courses',
            },
        ),
        migrations.CreateModel(
            name="CourseVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("origin_type", models.CharField(default="manual", max_length=16)),
                ("primary_locale", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(max_length=2000)),
                ("content_hash", models.CharField(max_length=71)),
                ("submitted_hash", models.CharField(blank=True, max_length=71, null=True)),
                ("approved_hash", models.CharField(blank=True, max_length=71, null=True)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="versions",
                        to="courses.course",
                    ),
                ),
                (
                    "predecessor_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="successor_versions",
                        to="courses.courseversion",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'app"."course_versions',
            },
        ),
        migrations.CreateModel(
            name="CoursePublicationReview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("decision", models.CharField(max_length=24)),
                ("reviewed_hash", models.CharField(max_length=71)),
                ("reviewer_id", models.UUIDField()),
                ("self_review", models.BooleanField(default=False)),
                ("reason_codes", models.JSONField(default=list)),
                ("decided_at", models.DateTimeField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
                (
                    "course_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="publication_reviews",
                        to="courses.courseversion",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."course_publication_reviews',
            },
        ),
        migrations.AddField(
            model_name="course",
            name="current_published_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="published_for_courses",
                to="courses.courseversion",
            ),
        ),
        migrations.CreateModel(
            name="CurriculumSection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("position", models.PositiveIntegerField()),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "course_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="courses.courseversion",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'app"."curriculum_sections',
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("position", models.PositiveIntegerField()),
                ("is_required", models.BooleanField(default=True)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "course_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.courseversion",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.curriculumsection",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'app"."lessons',
            },
        ),
        migrations.CreateModel(
            name="LessonContentBlock",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("kind", models.CharField(default="rich_text", max_length=16)),
                ("position", models.PositiveIntegerField()),
                ("document", models.JSONField()),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "course_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_blocks",
                        to="courses.courseversion",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_blocks",
                        to="courses.lesson",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'app"."lesson_content_blocks',
            },
        ),
        migrations.CreateModel(
            name="CourseInstructor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructors",
                        to="courses.course",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="instructed_courses",
                        to="tenancy.tenantmembership",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'app"."course_instructors',
                "indexes": [
                    models.Index(
                        fields=["tenant", "course", "membership"],
                        name="ix_instructors_tenant_course",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="uq_instructors_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "course", "membership"),
                        name="uq_instructors_course_member",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("row_version__gte", 1)),
                        name="ck_instructors_row_version",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="courseversion",
            index=models.Index(
                fields=["tenant", "course", "-version_number", "-id"],
                name="ix_versions_tenant_course_no",
            ),
        ),
        migrations.AddIndex(
            model_name="courseversion",
            index=models.Index(
                fields=["tenant", "status", "course"], name="ix_versions_tenant_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseversion",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_versions_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseversion",
            constraint=models.UniqueConstraint(
                fields=("tenant", "course", "id"), name="uq_versions_tenant_course_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseversion",
            constraint=models.UniqueConstraint(
                fields=("tenant", "course", "version_number"), name="uq_versions_tenant_course_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "draft",
                            "under_review",
                            "changes_requested",
                            "approved",
                            "scheduled",
                            "published",
                            "withdrawn",
                            "archived",
                        ),
                    )
                ),
                name="ck_versions_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("origin_type__in", ("manual", "ai_assisted"))),
                name="ck_versions_origin",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version_number__gte", 1)), name="ck_versions_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("row_version__gte", 1)), name="ck_versions_row_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_hash__regex", "^sha256:[0-9a-f]{64}$")),
                name="ck_versions_content_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("submitted_hash__isnull", True),
                    ("submitted_hash__regex", "^sha256:[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="ck_versions_submitted_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_hash__isnull", True),
                    ("approved_hash__regex", "^sha256:[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="ck_versions_approved_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_hash__isnull", True),
                    ("submitted_hash__isnull", False),
                    _connector="OR",
                ),
                name="ck_versions_hash_order",
            ),
        ),
        migrations.AddIndex(
            model_name="coursepublicationreview",
            index=models.Index(
                fields=["tenant", "course_version", "-decided_at", "-id"],
                name="ix_reviews_tenant_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursepublicationreview",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_reviews_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursepublicationreview",
            constraint=models.CheckConstraint(
                condition=models.Q(("decision__in", ("changes_requested", "approved"))),
                name="ck_reviews_decision",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursepublicationreview",
            constraint=models.CheckConstraint(
                condition=models.Q(("reviewed_hash__regex", "^sha256:[0-9a-f]{64}$")),
                name="ck_reviews_hash",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["tenant", "current_published_version"], name="ix_courses_tenant_current"
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_courses_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("tenant", "slug"), name="uq_courses_tenant_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reviewer_policy__in", ("self_review_allowed", "separate_reviewer_required"))
                ),
                name="ck_courses_reviewer_policy",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(("row_version__gte", 1)), name="ck_courses_row_version"
            ),
        ),
        migrations.AddIndex(
            model_name="curriculumsection",
            index=models.Index(
                fields=["tenant", "course_version", "position"], name="ix_sections_tenant_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumsection",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_sections_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumsection",
            constraint=models.UniqueConstraint(
                fields=("tenant", "course_version", "id"), name="uq_sections_tenant_ver_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumsection",
            constraint=models.UniqueConstraint(
                fields=("tenant", "course_version", "position"), name="uq_sections_version_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumsection",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)), name="ck_sections_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumsection",
            constraint=models.CheckConstraint(
                condition=models.Q(("row_version__gte", 1)), name="ck_sections_row_version"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["tenant", "section", "position"], name="ix_lessons_tenant_section"
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_lessons_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("tenant", "course_version", "id"), name="uq_lessons_tenant_ver_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("tenant", "section", "position"), name="uq_lessons_section_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)), name="ck_lessons_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.CheckConstraint(
                condition=models.Q(("row_version__gte", 1)), name="ck_lessons_row_version"
            ),
        ),
        migrations.AddIndex(
            model_name="lessoncontentblock",
            index=models.Index(
                fields=["tenant", "lesson", "position"], name="ix_blocks_tenant_lesson"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessoncontentblock",
            constraint=models.UniqueConstraint(fields=("tenant", "id"), name="uq_blocks_tenant_id"),
        ),
        migrations.AddConstraint(
            model_name="lessoncontentblock",
            constraint=models.UniqueConstraint(
                fields=("tenant", "lesson", "position"), name="uq_blocks_lesson_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessoncontentblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ("rich_text",))), name="ck_blocks_kind"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessoncontentblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)), name="ck_blocks_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessoncontentblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("row_version__gte", 1)), name="ck_blocks_row_version"
            ),
        ),
    ]
