# Generated by Django 6.1 on 2026-08-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_course_security"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="courseversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("predecessor_version__isnull", False)),
                fields=("tenant", "course", "predecessor_version"),
                name="uq_versions_one_successor",
            ),
        ),
    ]
