#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

from lms.api.main import app

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = REPO_ROOT / "contracts" / "openapi" / "openapi.json"


def render() -> str:
    schema = app.openapi()
    schema["$comment"] = "GENERATED by scripts/generate_openapi.py; DO NOT EDIT"
    schema["x-generated"] = "GENERATED by scripts/generate_openapi.py; DO NOT EDIT"
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()

    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("OpenAPI drift detected; run scripts/generate_openapi.py")
        print("OpenAPI 3.1 baseline is current.")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
