# Generated by Django 6.1 on 2026-08-31 08:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0005_ingestion_security"),
        ("tenancy", "0002_secure_invitation_bootstrap"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseBlueprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("schema_version", models.CharField(max_length=64)),
                ("status", models.CharField(default="reviewable", max_length=16)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(max_length=2000)),
                ("intended_audience", models.CharField(max_length=300)),
                ("prerequisites", models.JSONField(default=list)),
                ("learning_outcomes", models.JSONField(default=list)),
                ("projection", models.JSONField()),
                ("content_sha256", models.CharField(max_length=71)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'app"."course_generation_blueprints',
            },
        ),
        migrations.CreateModel(
            name="CourseGenerationRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("requested_by_actor_id", models.UUIDField()),
                ("status", models.CharField(default="queued", max_length=24)),
                ("target_level", models.CharField(max_length=16)),
                ("target_duration_minutes", models.PositiveIntegerField()),
                ("intended_audience", models.CharField(max_length=300)),
                ("teaching_style", models.CharField(max_length=16)),
                ("locale", models.CharField(default="en", max_length=8)),
                ("adapter", models.CharField(max_length=64)),
                ("provider", models.CharField(default="local_deterministic", max_length=32)),
                ("model", models.CharField(default="none", max_length=32)),
                ("normalized_schema_version", models.CharField(max_length=64)),
                ("blueprint_schema_version", models.CharField(max_length=64)),
                ("draft_schema_version", models.CharField(max_length=64)),
                ("policy_version", models.CharField(max_length=64)),
                ("prompt_template_sha256", models.CharField(max_length=71)),
                ("input_manifest_sha256", models.CharField(max_length=71)),
                (
                    "blueprint_content_sha256",
                    models.CharField(blank=True, max_length=71, null=True),
                ),
                ("output_manifest_sha256", models.CharField(blank=True, max_length=71, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("lease_owner", models.CharField(blank=True, max_length=80, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("checkpoint", models.CharField(default="created", max_length=64)),
                ("reason_code", models.CharField(blank=True, max_length=80, null=True)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "generate_authorization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="documents.sourceuseauthorization",
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="documents.documentingestionrun",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.sourcedocument"
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.sourceversion"
                    ),
                ),
                (
                    "supersedes_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="successor_runs",
                        to="course_generation.coursegenerationrun",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'integration"."course_generation_runs',
            },
        ),
        migrations.CreateModel(
            name="CourseGenerationAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                ("stage", models.CharField(max_length=24)),
                ("outcome", models.CharField(default="running", max_length=24)),
                ("reason_code", models.CharField(blank=True, max_length=80, null=True)),
                ("checkpoint", models.CharField(max_length=64)),
                ("input_manifest_sha256", models.CharField(max_length=71)),
                ("output_manifest_sha256", models.CharField(blank=True, max_length=71, null=True)),
                ("observation", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
                (
                    "generation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="attempts",
                        to="course_generation.coursegenerationrun",
                    ),
                ),
            ],
            options={
                "db_table": 'integration"."course_generation_attempts',
            },
        ),
        migrations.CreateModel(
            name="CourseBlueprintItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("kind", models.CharField(max_length=16)),
                ("position", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="items",
                        to="course_generation.courseblueprint",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="child_items",
                        to="course_generation.courseblueprintitem",
                    ),
                ),
                (
                    "source_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.documentsection"
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.sourceversion"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
                (
                    "generation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="course_generation.coursegenerationrun",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."course_generation_blueprint_items',
            },
        ),
        migrations.AddField(
            model_name="courseblueprint",
            name="generation_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="blueprints",
                to="course_generation.coursegenerationrun",
            ),
        ),
        migrations.CreateModel(
            name="BlueprintReviewDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("decided_by_actor_id", models.UUIDField()),
                ("decision", models.CharField(max_length=16)),
                ("reviewed_content_sha256", models.CharField(max_length=71)),
                ("reason_code", models.CharField(blank=True, max_length=80, null=True)),
                ("decided_at", models.DateTimeField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="course_generation.courseblueprint",
                    ),
                ),
                (
                    "generation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="course_generation.coursegenerationrun",
                    ),
                ),
            ],
            options={
                "db_table": 'audit"."course_generation_blueprint_decisions',
            },
        ),
        migrations.CreateModel(
            name="GeneratedLessonArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("schema_version", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=160)),
                ("document", models.JSONField()),
                ("content_sha256", models.CharField(max_length=71)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blueprint_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="course_generation.courseblueprintitem",
                    ),
                ),
                (
                    "generation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="lesson_artifacts",
                        to="course_generation.coursegenerationrun",
                    ),
                ),
                (
                    "source_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.documentsection"
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.sourceversion"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'app"."generated_lesson_artifacts',
            },
        ),
        migrations.CreateModel(
            name="GenerationRunSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("metadata", models.JSONField()),
                ("content_sha256", models.CharField(max_length=71)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generation_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="snapshot",
                        to="course_generation.coursegenerationrun",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'integration"."course_generation_snapshots',
            },
        ),
        migrations.CreateModel(
            name="GenerationSourceEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("edge_kind", models.CharField(max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blueprint_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="course_generation.courseblueprintitem",
                    ),
                ),
                (
                    "generated_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="course_generation.generatedlessonartifact",
                    ),
                ),
                (
                    "generation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="course_generation.coursegenerationrun",
                    ),
                ),
                (
                    "source_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.documentsection"
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.sourceversion"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'app"."course_generation_source_edges',
            },
        ),
        migrations.AddIndex(
            model_name="coursegenerationrun",
            index=models.Index(
                fields=["tenant", "status", "created_at"], name="ix_generation_claim"
            ),
        ),
        migrations.AddIndex(
            model_name="coursegenerationrun",
            index=models.Index(
                fields=["tenant", "source_version", "created_at"], name="ix_generation_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegenerationrun",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_generation_runs_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegenerationrun",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_version", "id"), name="uq_generation_runs_tenant_ver_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegenerationrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "queued",
                            "planning",
                            "blueprint_review",
                            "generation_queued",
                            "generating",
                            "review_ready",
                            "retryable",
                        ),
                    )
                ),
                fields=("tenant", "ingestion_run", "adapter"),
                name="uq_generation_runs_active_ingestion",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegenerationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "queued",
                            "planning",
                            "blueprint_review",
                            "generation_queued",
                            "generating",
                            "review_ready",
                            "canonicalized",
                            "rejected",
                            "retryable",
                            "failed",
                            "rights_blocked",
                        ),
                    )
                ),
                name="ck_generation_runs_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegenerationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_level__in", ("beginner", "intermediate", "advanced"))),
                name="ck_generation_runs_level",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegenerationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_duration_minutes__gte", 1), ("target_duration_minutes__lte", 10000)
                ),
                name="ck_generation_runs_duration",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegenerationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("teaching_style__in", ("concise", "guided", "reference"))),
                name="ck_generation_runs_style",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegenerationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("locale", "en")), name="ck_generation_locale"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegenerationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("model", "none"), ("provider", "local_deterministic")),
                name="ck_generation_local_provider",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegenerationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("input_manifest_sha256__regex", "^sha256:[0-9a-f]{64}$"),
                    ("prompt_template_sha256__regex", "^sha256:[0-9a-f]{64}$"),
                ),
                name="ck_generation_input_hashes",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegenerationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("blueprint_content_sha256__isnull", True),
                    ("blueprint_content_sha256__regex", "^sha256:[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="ck_generation_run_blueprint_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegenerationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("output_manifest_sha256__isnull", True),
                    ("output_manifest_sha256__regex", "^sha256:[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="ck_generation_output_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegenerationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_attempts__gte", 1),
                    ("max_attempts__lte", 10),
                    ("attempt_count__lte", models.F("max_attempts")),
                ),
                name="ck_generation_attempt_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegenerationrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("row_version__gte", 1)), name="ck_generation_runs_row_version"
            ),
        ),
        migrations.AddIndex(
            model_name="coursegenerationattempt",
            index=models.Index(
                fields=["tenant", "generation_run", "attempt_number"],
                name="ix_generation_attempts_run",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegenerationattempt",
            constraint=models.UniqueConstraint(
                fields=("tenant", "generation_run", "attempt_number"),
                name="uq_generation_attempts_run_no",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegenerationattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "outcome__in",
                        ("running", "completed", "retryable", "failed", "rights_blocked"),
                    )
                ),
                name="ck_generation_attempts_outcome",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegenerationattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_manifest_sha256__regex", "^sha256:[0-9a-f]{64}$")),
                name="ck_generation_attempt_input",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseblueprintitem",
            constraint=models.UniqueConstraint(
                fields=("tenant", "blueprint", "id"), name="uq_generation_items_blueprint_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseblueprintitem",
            constraint=models.UniqueConstraint(
                fields=("tenant", "blueprint", "kind", "parent", "position"),
                name="uq_generation_items_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseblueprintitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ("module", "lesson"))),
                name="ck_generation_items_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseblueprintitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "module"), ("parent__isnull", True)),
                    models.Q(("kind", "lesson"), ("parent__isnull", False)),
                    _connector="OR",
                ),
                name="ck_generation_items_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseblueprintitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)),
                name="ck_generation_items_positive_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseblueprint",
            constraint=models.UniqueConstraint(
                fields=("tenant", "generation_run", "revision"),
                name="uq_generation_blueprints_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseblueprint",
            constraint=models.UniqueConstraint(
                fields=("tenant", "generation_run", "id"), name="uq_generation_blueprints_run_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseblueprint",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("reviewable", "approved", "rejected"))),
                name="ck_generation_blueprint_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseblueprint",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_sha256__regex", "^sha256:[0-9a-f]{64}$")),
                name="ck_generation_blueprint_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="blueprintreviewdecision",
            constraint=models.UniqueConstraint(
                fields=("tenant", "generation_run", "blueprint"),
                name="uq_generation_decisions_blueprint",
            ),
        ),
        migrations.AddConstraint(
            model_name="blueprintreviewdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("decision__in", ("approve", "reject"))),
                name="ck_generation_decisions_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="blueprintreviewdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("reviewed_content_sha256__regex", "^sha256:[0-9a-f]{64}$")),
                name="ck_generation_decisions_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="blueprintreviewdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("decision", "approve"), ("reason_code__isnull", True)),
                    models.Q(("decision", "reject"), ("reason_code__isnull", False)),
                    _connector="OR",
                ),
                name="ck_generation_decisions_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedlessonartifact",
            constraint=models.UniqueConstraint(
                fields=("tenant", "generation_run", "blueprint_item", "revision"),
                name="uq_generated_lessons_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedlessonartifact",
            constraint=models.UniqueConstraint(
                fields=("tenant", "generation_run", "id"), name="uq_generated_lessons_run_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedlessonartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="ck_generated_lessons_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedlessonartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_sha256__regex", "^sha256:[0-9a-f]{64}$")),
                name="ck_generated_lessons_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="generationrunsnapshot",
            constraint=models.UniqueConstraint(
                fields=("tenant", "generation_run"), name="uq_generation_snapshots_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="generationrunsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_sha256__regex", "^sha256:[0-9a-f]{64}$")),
                name="ck_generation_snapshot_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="generationsourceedge",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_generation_edges_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="generationsourceedge",
            constraint=models.CheckConstraint(
                condition=models.Q(("edge_kind__in", ("blueprint_item", "generated_lesson"))),
                name="ck_generation_edges_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="generationsourceedge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("blueprint_item__isnull", False),
                        ("edge_kind", "blueprint_item"),
                        ("generated_artifact__isnull", True),
                    ),
                    models.Q(
                        ("blueprint_item__isnull", True),
                        ("edge_kind", "generated_lesson"),
                        ("generated_artifact__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_generation_edges_target",
            ),
        ),
    ]
