# Generated by Django 6.1 on 2026-08-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_generation", "0001_generation_schema"),
        ("documents", "0005_ingestion_security"),
        ("tenancy", "0002_secure_invitation_bootstrap"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="blueprintreviewdecision",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_generation_decisions_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseblueprint",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_generation_blueprints_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseblueprintitem",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_generation_items_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseblueprintitem",
            constraint=models.UniqueConstraint(
                fields=("tenant", "generation_run", "id"), name="uq_generation_items_run_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegenerationattempt",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_generation_attempts_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedlessonartifact",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_generated_lessons_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="generationrunsnapshot",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_generation_snapshots_tenant_id"
            ),
        ),
    ]
