# Generated by Django 6.1 on 2026-08-31 08:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_generation", "0002_generation_tenant_keys"),
        ("tenancy", "0002_secure_invitation_bootstrap"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseGenerationRejection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("rejected_by_actor_id", models.UUIDField()),
                ("reviewed_output_sha256", models.CharField(max_length=71)),
                ("reason_code", models.CharField(max_length=80)),
                ("rejected_at", models.DateTimeField()),
                (
                    "generation_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="rejection",
                        to="course_generation.coursegenerationrun",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'audit"."course_generation_rejections',
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="uq_generation_rejections_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "generation_run"), name="uq_generation_rejections_run"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reviewed_output_sha256__regex", "^sha256:[0-9a-f]{64}$")
                        ),
                        name="ck_generation_rejections_hash",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "reason_code__in",
                                (
                                    "GENERATION_CONTENT_REJECTED",
                                    "GENERATION_SOURCE_ALIGNMENT_REJECTED",
                                ),
                            )
                        ),
                        name="ck_generation_rejections_reason",
                    ),
                ],
            },
        ),
    ]
