# Generated by Django 6.1 on 2026-08-31 14:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_generation", "0004_generation_security"),
        ("courses", "0003_one_successor"),
        ("documents", "0005_ingestion_security"),
        ("tenancy", "0002_secure_invitation_bootstrap"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationCanonicalization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("canonicalized_by_actor_id", models.UUIDField()),
                ("requested_course_slug", models.SlugField(max_length=63)),
                ("reviewed_output_sha256", models.CharField(max_length=71)),
                ("canonical_content_sha256", models.CharField(max_length=71)),
                ("canonicalization_sha256", models.CharField(max_length=71)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="courses.course"
                    ),
                ),
                (
                    "course_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="courses.courseversion"
                    ),
                ),
                (
                    "generation_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="canonicalization",
                        to="course_generation.coursegenerationrun",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'audit"."course_generation_canonicalizations',
            },
        ),
        migrations.CreateModel(
            name="CanonicalizationSourceEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content_block_id", models.UUIDField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="courses.course"
                    ),
                ),
                (
                    "course_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="courses.courseversion"
                    ),
                ),
                ("curriculum_section_id", models.UUIDField()),
                (
                    "generated_artifact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="canonicalization_edge",
                        to="course_generation.generatedlessonartifact",
                    ),
                ),
                (
                    "generation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="course_generation.coursegenerationrun",
                    ),
                ),
                ("lesson_id", models.UUIDField()),
                (
                    "source_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.documentsection"
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="documents.sourceversion"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
                (
                    "canonicalization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="source_edges",
                        to="course_generation.generationcanonicalization",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."course_generation_canonicalization_edges',
            },
        ),
        migrations.AddConstraint(
            model_name="generationcanonicalization",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_generation_canonical_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="generationcanonicalization",
            constraint=models.UniqueConstraint(
                fields=("tenant", "generation_run"), name="uq_generation_canonical_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="generationcanonicalization",
            constraint=models.UniqueConstraint(
                fields=("tenant", "course"), name="uq_generation_canonical_course"
            ),
        ),
        migrations.AddConstraint(
            model_name="generationcanonicalization",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reviewed_output_sha256__regex", "^sha256:[0-9a-f]{64}$"),
                    ("canonical_content_sha256__regex", "^sha256:[0-9a-f]{64}$"),
                    ("canonicalization_sha256__regex", "^sha256:[0-9a-f]{64}$"),
                ),
                name="ck_generation_canonical_hashes",
            ),
        ),
        migrations.AddConstraint(
            model_name="canonicalizationsourceedge",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_canonical_edges_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="canonicalizationsourceedge",
            constraint=models.UniqueConstraint(
                fields=("tenant", "canonicalization", "generated_artifact"),
                name="uq_canonical_edges_artifact",
            ),
        ),
        migrations.AddConstraint(
            model_name="canonicalizationsourceedge",
            constraint=models.UniqueConstraint(
                fields=("tenant", "canonicalization", "content_block_id"),
                name="uq_canonical_edges_block",
            ),
        ),
    ]
