# Generated by Django 6.1 on 2026-08-11 12:23

import uuid

import django.db.models.deletion
from django.db import migrations, models

PERMISSIONS = (
    ("tenancy.memberships.read", "List tenant memberships"),
    ("tenancy.invitations.create", "Create tenant invitations"),
    ("tenancy.memberships.update", "Update membership state and fixed roles"),
)


def seed_permissions(apps, schema_editor):
    Permission = apps.get_model("tenancy", "Permission")
    for code, description in PERMISSIONS:
        Permission.objects.get_or_create(
            id=uuid.uuid5(uuid.NAMESPACE_URL, f"ai-lms:permission:{code}"),
            defaults={"code": code, "description": description},
        )


def unseed_permissions(apps, schema_editor):
    # The same reverse migration drops the permissions table. Deleting rows
    # first would leave pending FK trigger events and prevent that table drop.
    del apps, schema_editor


SECURITY_SQL = r"""
ALTER TABLE app.tenants OWNER TO lms_object_owner;
ALTER TABLE app.entitlement_periods OWNER TO lms_object_owner;
ALTER TABLE app.tenant_memberships OWNER TO lms_object_owner;
ALTER TABLE app.roles OWNER TO lms_object_owner;
ALTER TABLE app.permissions OWNER TO lms_object_owner;
ALTER TABLE app.role_permissions OWNER TO lms_object_owner;
ALTER TABLE app.membership_roles OWNER TO lms_object_owner;
ALTER TABLE app.tenant_invitations OWNER TO lms_object_owner;
ALTER TABLE app.tenant_invitation_roles OWNER TO lms_object_owner;
ALTER TABLE audit.tenant_audit_facts OWNER TO lms_object_owner;
ALTER TABLE integration.idempotency_reservations OWNER TO lms_object_owner;
ALTER TABLE integration.tenant_outbox_facts OWNER TO lms_object_owner;

REVOKE ALL ON ALL TABLES IN SCHEMA app, audit, integration FROM PUBLIC;
GRANT USAGE ON SCHEMA audit, integration TO lms_api_runtime;

ALTER TABLE app.role_permissions
    ADD CONSTRAINT fk_role_permissions_same_tenant_role
    FOREIGN KEY (tenant_id, role_id) REFERENCES app.roles (tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE app.membership_roles
    ADD CONSTRAINT fk_membership_roles_same_tenant_membership
    FOREIGN KEY (tenant_id, membership_id)
    REFERENCES app.tenant_memberships (tenant_id, id) ON DELETE CASCADE;
ALTER TABLE app.membership_roles
    ADD CONSTRAINT fk_membership_roles_same_tenant_role
    FOREIGN KEY (tenant_id, role_id) REFERENCES app.roles (tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE app.tenant_invitation_roles
    ADD CONSTRAINT fk_invitation_roles_same_tenant_invitation
    FOREIGN KEY (tenant_id, invitation_id)
    REFERENCES app.tenant_invitations (tenant_id, id) ON DELETE CASCADE;
ALTER TABLE app.tenant_invitation_roles
    ADD CONSTRAINT fk_invitation_roles_same_tenant_role
    FOREIGN KEY (tenant_id, role_id) REFERENCES app.roles (tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE app.tenant_invitations
    ADD CONSTRAINT fk_invitations_same_tenant_membership
    FOREIGN KEY (tenant_id, accepted_membership_id)
    REFERENCES app.tenant_memberships (tenant_id, id) ON DELETE RESTRICT;

CREATE OR REPLACE FUNCTION app.current_actor_id()
RETURNS uuid
LANGUAGE sql
STABLE
SET search_path = pg_catalog
AS $$
    SELECT NULLIF(current_setting('app.current_actor_id', true), '')::uuid
$$;

CREATE OR REPLACE FUNCTION app.current_tenant_id()
RETURNS uuid
LANGUAGE sql
STABLE
SET search_path = pg_catalog
AS $$
    SELECT NULLIF(current_setting('app.current_tenant_id', true), '')::uuid
$$;

CREATE OR REPLACE FUNCTION app.current_user_profile_id()
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, app
SET row_security = off
AS $$
    SELECT id
      FROM app.user_profiles
     WHERE provider_subject = app.current_actor_id()
       AND status = 'active'
$$;

CREATE OR REPLACE FUNCTION app.has_invitation_access(target_tenant_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, app
SET row_security = off
AS $$
    SELECT app.current_actor_id() IS NOT NULL
       AND EXISTS (
            SELECT 1
              FROM app.tenant_invitations invitation
             WHERE invitation.tenant_id = target_tenant_id
               AND invitation.token_digest =
                   NULLIF(current_setting('app.current_invitation_digest', true), '')
               AND invitation.status IN ('active', 'accepted')
       )
$$;

CREATE OR REPLACE FUNCTION app.has_active_membership_candidate(target_tenant_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, app
SET row_security = off
AS $$
    SELECT EXISTS (
            SELECT 1
              FROM app.tenants tenant
              JOIN app.tenant_memberships membership
                ON membership.tenant_id = tenant.id
               AND membership.user_profile_id = app.current_user_profile_id()
               AND membership.status = 'active'
              JOIN app.entitlement_periods entitlement
                ON entitlement.tenant_id = tenant.id
               AND entitlement.status = 'active'
               AND entitlement.starts_at <= transaction_timestamp()
               AND (entitlement.valid_until IS NULL
                    OR entitlement.valid_until > transaction_timestamp())
             WHERE tenant.id = target_tenant_id
               AND tenant.status = 'active'
       )
$$;

CREATE OR REPLACE FUNCTION app.has_active_tenant_access(target_tenant_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, app
SET row_security = off
AS $$
    SELECT target_tenant_id = app.current_tenant_id()
       AND app.has_active_membership_candidate(target_tenant_id)
$$;

CREATE OR REPLACE FUNCTION app.has_permission(target_tenant_id uuid, permission_key text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, app
SET row_security = off
AS $$
    SELECT app.has_active_tenant_access(target_tenant_id)
       AND EXISTS (
            SELECT 1
              FROM app.tenant_memberships membership
              JOIN app.membership_roles membership_role
                ON membership_role.tenant_id = membership.tenant_id
               AND membership_role.membership_id = membership.id
              JOIN app.role_permissions role_permission
                ON role_permission.tenant_id = membership_role.tenant_id
               AND role_permission.role_id = membership_role.role_id
              JOIN app.permissions permission
                ON permission.id = role_permission.permission_id
             WHERE membership.tenant_id = target_tenant_id
               AND membership.user_profile_id = app.current_user_profile_id()
               AND membership.status = 'active'
               AND permission.code = permission_key
       )
$$;

-- Security-definer policy helpers deliberately remain owned by the one-off
-- migrator. The non-login table owner is itself subject to FORCE RLS and cannot
-- safely perform the required non-recursive authorization lookup. PUBLIC has no
-- execute grant and runtime can invoke only these fixed-search-path predicates.
REVOKE ALL ON FUNCTION app.current_actor_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION app.current_tenant_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION app.current_user_profile_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION app.has_invitation_access(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION app.has_active_membership_candidate(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION app.has_active_tenant_access(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION app.has_permission(uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app.current_actor_id(), app.current_tenant_id(),
    app.current_user_profile_id(), app.has_invitation_access(uuid),
    app.has_active_membership_candidate(uuid), app.has_active_tenant_access(uuid),
    app.has_permission(uuid, text)
    TO lms_api_runtime;

ALTER TABLE app.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.tenants FORCE ROW LEVEL SECURITY;
CREATE POLICY tenants_select ON app.tenants FOR SELECT TO lms_api_runtime
    USING (
        app.has_active_tenant_access(id)
        OR (app.current_tenant_id() IS NULL AND app.has_active_membership_candidate(id))
        OR app.has_invitation_access(id)
    );

ALTER TABLE app.entitlement_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.entitlement_periods FORCE ROW LEVEL SECURITY;
CREATE POLICY entitlements_select ON app.entitlement_periods FOR SELECT TO lms_api_runtime
    USING (
        app.has_active_tenant_access(tenant_id)
        OR (app.current_tenant_id() IS NULL
            AND app.has_active_membership_candidate(tenant_id))
    );

ALTER TABLE app.tenant_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.tenant_memberships FORCE ROW LEVEL SECURITY;
CREATE POLICY memberships_select ON app.tenant_memberships FOR SELECT TO lms_api_runtime
    USING (
        (user_profile_id = app.current_user_profile_id()
         AND app.has_active_membership_candidate(tenant_id)
         AND (app.current_tenant_id() IS NULL OR tenant_id = app.current_tenant_id()))
        OR app.has_permission(tenant_id, 'tenancy.memberships.read')
        OR (app.has_invitation_access(tenant_id)
            AND user_profile_id = app.current_user_profile_id())
    );
CREATE POLICY memberships_insert ON app.tenant_memberships FOR INSERT TO lms_api_runtime
    WITH CHECK (
        (app.has_invitation_access(tenant_id)
         AND user_profile_id = app.current_user_profile_id())
        OR app.has_permission(tenant_id, 'tenancy.memberships.update')
    );
CREATE POLICY memberships_update ON app.tenant_memberships FOR UPDATE TO lms_api_runtime
    USING (
        app.has_permission(tenant_id, 'tenancy.memberships.update')
        OR (app.has_invitation_access(tenant_id)
            AND user_profile_id = app.current_user_profile_id())
    )
    WITH CHECK (
        app.has_permission(tenant_id, 'tenancy.memberships.update')
        OR (app.has_invitation_access(tenant_id)
            AND user_profile_id = app.current_user_profile_id())
    );

ALTER TABLE app.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.roles FORCE ROW LEVEL SECURITY;
CREATE POLICY roles_select ON app.roles FOR SELECT TO lms_api_runtime
    USING (app.has_active_tenant_access(tenant_id) OR app.has_invitation_access(tenant_id));

ALTER TABLE app.role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.role_permissions FORCE ROW LEVEL SECURITY;
CREATE POLICY role_permissions_select ON app.role_permissions FOR SELECT TO lms_api_runtime
    USING (app.has_active_tenant_access(tenant_id));

ALTER TABLE app.membership_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.membership_roles FORCE ROW LEVEL SECURITY;
CREATE POLICY membership_roles_select ON app.membership_roles FOR SELECT TO lms_api_runtime
    USING (
        app.has_permission(tenant_id, 'tenancy.memberships.read')
        OR EXISTS (
            SELECT 1 FROM app.tenant_memberships membership
             WHERE membership.id = membership_id
               AND membership.tenant_id = tenant_id
               AND membership.user_profile_id = app.current_user_profile_id()
        )
        OR app.has_invitation_access(tenant_id)
    );
CREATE POLICY membership_roles_insert ON app.membership_roles FOR INSERT TO lms_api_runtime
    WITH CHECK (
        app.has_permission(tenant_id, 'tenancy.memberships.update')
        OR (app.has_invitation_access(tenant_id) AND EXISTS (
            SELECT 1 FROM app.tenant_memberships membership
             WHERE membership.id = membership_id
               AND membership.tenant_id = tenant_id
               AND membership.user_profile_id = app.current_user_profile_id()
        ))
    );
CREATE POLICY membership_roles_delete ON app.membership_roles FOR DELETE TO lms_api_runtime
    USING (
        app.has_permission(tenant_id, 'tenancy.memberships.update')
        OR (app.has_invitation_access(tenant_id) AND EXISTS (
            SELECT 1 FROM app.tenant_memberships membership
             WHERE membership.id = membership_id
               AND membership.tenant_id = tenant_id
               AND membership.user_profile_id = app.current_user_profile_id()
        ))
    );

ALTER TABLE app.tenant_invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.tenant_invitations FORCE ROW LEVEL SECURITY;
CREATE POLICY invitations_select ON app.tenant_invitations FOR SELECT TO lms_api_runtime
    USING (
        app.has_permission(tenant_id, 'tenancy.invitations.create')
        OR app.has_invitation_access(tenant_id)
    );
CREATE POLICY invitations_insert ON app.tenant_invitations FOR INSERT TO lms_api_runtime
    WITH CHECK (app.has_permission(tenant_id, 'tenancy.invitations.create'));
CREATE POLICY invitations_update ON app.tenant_invitations FOR UPDATE TO lms_api_runtime
    USING (
        app.has_permission(tenant_id, 'tenancy.invitations.create')
        OR app.has_invitation_access(tenant_id)
    )
    WITH CHECK (
        app.has_permission(tenant_id, 'tenancy.invitations.create')
        OR app.has_invitation_access(tenant_id)
    );

ALTER TABLE app.tenant_invitation_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.tenant_invitation_roles FORCE ROW LEVEL SECURITY;
CREATE POLICY invitation_roles_select ON app.tenant_invitation_roles FOR SELECT TO lms_api_runtime
    USING (
        app.has_permission(tenant_id, 'tenancy.invitations.create')
        OR app.has_invitation_access(tenant_id)
    );
CREATE POLICY invitation_roles_insert ON app.tenant_invitation_roles FOR INSERT TO lms_api_runtime
    WITH CHECK (app.has_permission(tenant_id, 'tenancy.invitations.create'));

ALTER TABLE audit.tenant_audit_facts ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit.tenant_audit_facts FORCE ROW LEVEL SECURITY;
CREATE POLICY audit_insert ON audit.tenant_audit_facts FOR INSERT TO lms_api_runtime
    WITH CHECK (
        tenant_id = app.current_tenant_id()
        AND (
            app.has_permission(tenant_id, 'tenancy.invitations.create')
            OR app.has_permission(tenant_id, 'tenancy.memberships.update')
            OR app.has_invitation_access(tenant_id)
        )
    );

ALTER TABLE integration.idempotency_reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE integration.idempotency_reservations FORCE ROW LEVEL SECURITY;
CREATE POLICY idempotency_all ON integration.idempotency_reservations
    FOR ALL TO lms_api_runtime
    USING (
        actor_id = app.current_actor_id()
        AND app.has_permission(tenant_id, 'tenancy.invitations.create')
    )
    WITH CHECK (
        actor_id = app.current_actor_id()
        AND app.has_permission(tenant_id, 'tenancy.invitations.create')
    );

ALTER TABLE integration.tenant_outbox_facts ENABLE ROW LEVEL SECURITY;
ALTER TABLE integration.tenant_outbox_facts FORCE ROW LEVEL SECURITY;
CREATE POLICY outbox_insert ON integration.tenant_outbox_facts FOR INSERT TO lms_api_runtime
    WITH CHECK (
        tenant_id = app.current_tenant_id()
        AND (
            app.has_permission(tenant_id, 'tenancy.invitations.create')
            OR app.has_permission(tenant_id, 'tenancy.memberships.update')
            OR app.has_invitation_access(tenant_id)
        )
    );

CREATE OR REPLACE FUNCTION audit.reject_fact_mutation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $$
BEGIN
    RAISE EXCEPTION 'immutable fact rows cannot be changed' USING ERRCODE = '55000';
END
$$;
ALTER FUNCTION audit.reject_fact_mutation() OWNER TO lms_object_owner;
REVOKE ALL ON FUNCTION audit.reject_fact_mutation() FROM PUBLIC;
CREATE TRIGGER audit_facts_immutable
BEFORE UPDATE OR DELETE ON audit.tenant_audit_facts
FOR EACH ROW EXECUTE FUNCTION audit.reject_fact_mutation();
CREATE TRIGGER outbox_facts_immutable
BEFORE UPDATE OR DELETE ON integration.tenant_outbox_facts
FOR EACH ROW EXECUTE FUNCTION audit.reject_fact_mutation();

GRANT SELECT ON app.tenants, app.entitlement_periods, app.tenant_memberships,
    app.roles, app.permissions, app.role_permissions, app.membership_roles,
    app.tenant_invitations, app.tenant_invitation_roles TO lms_api_runtime;
GRANT INSERT, UPDATE, DELETE ON app.tenant_memberships TO lms_api_runtime;
GRANT INSERT, DELETE ON app.membership_roles TO lms_api_runtime;
GRANT INSERT, UPDATE ON app.tenant_invitations TO lms_api_runtime;
GRANT INSERT ON app.tenant_invitation_roles TO lms_api_runtime;
GRANT SELECT, INSERT, UPDATE ON integration.idempotency_reservations TO lms_api_runtime;
GRANT INSERT ON audit.tenant_audit_facts, integration.tenant_outbox_facts TO lms_api_runtime;
"""


REVERSE_SECURITY_SQL = r"""
REVOKE USAGE ON SCHEMA audit, integration FROM lms_api_runtime;
REVOKE ALL ON app.user_profiles, app.tenants, app.entitlement_periods,
    app.tenant_memberships, app.roles, app.permissions, app.role_permissions,
    app.membership_roles, app.tenant_invitations, app.tenant_invitation_roles,
    audit.tenant_audit_facts, integration.idempotency_reservations,
    integration.tenant_outbox_facts FROM lms_api_runtime;
DROP TRIGGER IF EXISTS outbox_facts_immutable ON integration.tenant_outbox_facts;
DROP TRIGGER IF EXISTS audit_facts_immutable ON audit.tenant_audit_facts;
DROP POLICY IF EXISTS outbox_insert ON integration.tenant_outbox_facts;
DROP POLICY IF EXISTS idempotency_all ON integration.idempotency_reservations;
DROP POLICY IF EXISTS audit_insert ON audit.tenant_audit_facts;
DROP POLICY IF EXISTS invitation_roles_insert ON app.tenant_invitation_roles;
DROP POLICY IF EXISTS invitation_roles_select ON app.tenant_invitation_roles;
DROP POLICY IF EXISTS invitations_update ON app.tenant_invitations;
DROP POLICY IF EXISTS invitations_insert ON app.tenant_invitations;
DROP POLICY IF EXISTS invitations_select ON app.tenant_invitations;
DROP POLICY IF EXISTS membership_roles_delete ON app.membership_roles;
DROP POLICY IF EXISTS membership_roles_insert ON app.membership_roles;
DROP POLICY IF EXISTS membership_roles_select ON app.membership_roles;
DROP POLICY IF EXISTS role_permissions_select ON app.role_permissions;
DROP POLICY IF EXISTS roles_select ON app.roles;
DROP POLICY IF EXISTS memberships_update ON app.tenant_memberships;
DROP POLICY IF EXISTS memberships_insert ON app.tenant_memberships;
DROP POLICY IF EXISTS memberships_select ON app.tenant_memberships;
DROP POLICY IF EXISTS entitlements_select ON app.entitlement_periods;
DROP POLICY IF EXISTS tenants_select ON app.tenants;
DROP FUNCTION IF EXISTS audit.reject_fact_mutation();
DROP FUNCTION IF EXISTS app.has_permission(uuid, text);
DROP FUNCTION IF EXISTS app.has_active_tenant_access(uuid);
DROP FUNCTION IF EXISTS app.has_active_membership_candidate(uuid);
DROP FUNCTION IF EXISTS app.has_invitation_access(uuid);
DROP FUNCTION IF EXISTS app.current_user_profile_id();
DROP FUNCTION IF EXISTS app.current_tenant_id();
DROP FUNCTION IF EXISTS app.current_actor_id();
ALTER TABLE app.tenant_invitations DROP CONSTRAINT IF EXISTS fk_invitations_same_tenant_membership;
ALTER TABLE app.tenant_invitation_roles DROP CONSTRAINT IF EXISTS fk_invitation_roles_same_tenant_role;
ALTER TABLE app.tenant_invitation_roles DROP CONSTRAINT IF EXISTS fk_invitation_roles_same_tenant_invitation;
ALTER TABLE app.membership_roles DROP CONSTRAINT IF EXISTS fk_membership_roles_same_tenant_role;
ALTER TABLE app.membership_roles DROP CONSTRAINT IF EXISTS fk_membership_roles_same_tenant_membership;
ALTER TABLE app.role_permissions DROP CONSTRAINT IF EXISTS fk_role_permissions_same_tenant_role;
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lms_identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=96, unique=True)),
                ("description", models.CharField(max_length=200)),
            ],
            options={
                "db_table": 'app"."permissions',
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(max_length=63, unique=True)),
                ("display_name", models.CharField(max_length=120)),
                ("status", models.CharField(default="active", max_length=16)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
            ],
            options={
                "db_table": 'app"."tenants',
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ("active", "inactive", "suspended"))),
                        name="ck_tenants_status",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("display_name", models.CharField(max_length=80)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="roles",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."roles',
            },
        ),
        migrations.CreateModel(
            name="OutboxFact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_type", models.CharField(max_length=96)),
                ("aggregate_type", models.CharField(max_length=64)),
                ("aggregate_id", models.UUIDField()),
                ("actor_id", models.UUIDField()),
                ("request_id", models.UUIDField(default=uuid.uuid4)),
                ("payload", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'integration"."tenant_outbox_facts',
            },
        ),
        migrations.CreateModel(
            name="IdempotencyReservation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actor_id", models.UUIDField()),
                ("operation", models.CharField(max_length=64)),
                ("key_digest", models.CharField(max_length=64)),
                ("request_hash", models.CharField(max_length=64)),
                ("status", models.CharField(default="reserved", max_length=16)),
                ("response_payload", models.JSONField(default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'integration"."idempotency_reservations',
            },
        ),
        migrations.CreateModel(
            name="EntitlementPeriod",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("status", models.CharField(default="active", max_length=16)),
                ("starts_at", models.DateTimeField()),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="entitlements",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."entitlement_periods',
            },
        ),
        migrations.CreateModel(
            name="AuditFact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_type", models.CharField(max_length=96)),
                ("actor_id", models.UUIDField()),
                ("subject_type", models.CharField(max_length=64)),
                ("subject_id", models.UUIDField()),
                ("request_id", models.UUIDField(default=uuid.uuid4)),
                ("payload", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'audit"."tenant_audit_facts',
            },
        ),
        migrations.CreateModel(
            name="TenantInvitation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token_digest", models.CharField(editable=False, max_length=64, unique=True)),
                ("status", models.CharField(default="active", max_length=16)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="accepted_tenant_invitations",
                        to="lms_identity.userprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="invitations",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."tenant_invitations',
            },
        ),
        migrations.CreateModel(
            name="TenantInvitationRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_links",
                        to="tenancy.tenantinvitation",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.role"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'app"."tenant_invitation_roles',
            },
        ),
        migrations.CreateModel(
            name="TenantMembership",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("status", models.CharField(default="active", max_length=16)),
                ("row_version", models.PositiveBigIntegerField(default=1)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="memberships",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="tenant_memberships",
                        to="lms_identity.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."tenant_memberships',
            },
        ),
        migrations.AddField(
            model_name="tenantinvitation",
            name="accepted_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="accepted_invitations",
                to="tenancy.tenantmembership",
            ),
        ),
        migrations.CreateModel(
            name="MembershipRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="membership_links",
                        to="tenancy.role",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_links",
                        to="tenancy.tenantmembership",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."membership_roles',
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.permission"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="permission_links",
                        to="tenancy.role",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "db_table": 'app"."role_permissions',
                "indexes": [
                    models.Index(
                        fields=["tenant", "role", "permission"], name="ix_role_permissions_lookup"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="uq_role_permissions_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "role", "permission"), name="uq_role_permissions_edge"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["tenant", "code"], name="ix_roles_tenant_code"),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(fields=("tenant", "id"), name="uq_roles_tenant_id"),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_roles_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("code__in", ("tenant_admin", "instructor", "reviewer", "learner"))
                ),
                name="ck_roles_fixed_code",
            ),
        ),
        migrations.AddIndex(
            model_name="outboxfact",
            index=models.Index(fields=["tenant", "occurred_at"], name="ix_outbox_tenant_time"),
        ),
        migrations.AddConstraint(
            model_name="outboxfact",
            constraint=models.UniqueConstraint(fields=("tenant", "id"), name="uq_outbox_tenant_id"),
        ),
        migrations.AddIndex(
            model_name="idempotencyreservation",
            index=models.Index(
                fields=["tenant", "actor_id", "operation", "key_digest"],
                name="ix_idempotency_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyreservation",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_idempotency_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyreservation",
            constraint=models.UniqueConstraint(
                fields=("tenant", "actor_id", "operation", "key_digest"),
                name="uq_idempotency_operation_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("reserved", "completed"))),
                name="ck_idempotency_status",
            ),
        ),
        migrations.AddIndex(
            model_name="entitlementperiod",
            index=models.Index(
                fields=["tenant", "status", "starts_at", "valid_until"],
                name="ix_entitlements_access",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitlementperiod",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_entitlements_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="entitlementperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("active", "expired", "suspended"))),
                name="ck_entitlements_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitlementperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("valid_until__gt", models.F("starts_at")),
                    _connector="OR",
                ),
                name="ck_entitlements_time_range",
            ),
        ),
        migrations.AddIndex(
            model_name="auditfact",
            index=models.Index(fields=["tenant", "occurred_at"], name="ix_audit_tenant_time"),
        ),
        migrations.AddConstraint(
            model_name="auditfact",
            constraint=models.UniqueConstraint(fields=("tenant", "id"), name="uq_audit_tenant_id"),
        ),
        migrations.AddIndex(
            model_name="tenantinvitationrole",
            index=models.Index(
                fields=["tenant", "invitation", "role"], name="ix_invitation_roles_lookup"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantinvitationrole",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_invitation_roles_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantinvitationrole",
            constraint=models.UniqueConstraint(
                fields=("tenant", "invitation", "role"), name="uq_invitation_roles_edge"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantmembership",
            index=models.Index(
                fields=["tenant", "status", "user_profile"], name="ix_memberships_access"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantmembership",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_memberships_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantmembership",
            constraint=models.UniqueConstraint(
                fields=("tenant", "user_profile"), name="uq_memberships_tenant_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantmembership",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("active", "inactive"))),
                name="ck_memberships_status",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantinvitation",
            index=models.Index(fields=["tenant", "status", "expires_at"], name="ix_invites_active"),
        ),
        migrations.AddConstraint(
            model_name="tenantinvitation",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_invitations_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantinvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("active", "accepted", "expired", "revoked"))),
                name="ck_invitations_status",
            ),
        ),
        migrations.AddIndex(
            model_name="membershiprole",
            index=models.Index(
                fields=["tenant", "membership", "role"], name="ix_membership_roles_lookup"
            ),
        ),
        migrations.AddConstraint(
            model_name="membershiprole",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="uq_membership_roles_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="membershiprole",
            constraint=models.UniqueConstraint(
                fields=("tenant", "membership", "role"), name="uq_membership_roles_edge"
            ),
        ),
        migrations.RunPython(seed_permissions, unseed_permissions),
        migrations.RunSQL(sql=SECURITY_SQL, reverse_sql=REVERSE_SECURITY_SQL),
    ]
